<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employees_code' => 1,
                'zketo_code' => 1001,
                'emp_name' => 'Ahmet Yilmaz',
                'emp_gender' => 1,
                'branch_id' => 1,
                'emp_email' => 'ahmet.yilmaz@example.com',
                'emp_home_tel' => '02120000001',
                'emp_work_tel' => '08500000001',
                'notes' => 'Demo employee 1',
                'emp_start_date' => '2023-01-10',
                'Functiona_status' => 1,
                'emp_Departments_code' => 1,
                'emp_jobs_id' => 1,
                'shift_type_id' => 1,
                'emp_sal' => 18000,
                'staies_address' => 'Istanbul / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 2,
                'zketo_code' => 1002,
                'emp_name' => 'Ayse Demir',
                'emp_gender' => 2,
                'branch_id' => 2,
                'emp_email' => 'ayse.demir@example.com',
                'emp_home_tel' => '02120000002',
                'emp_work_tel' => '08500000002',
                'notes' => 'Demo employee 2',
                'emp_start_date' => '2023-02-15',
                'Functiona_status' => 1,
                'emp_Departments_code' => 2,
                'emp_jobs_id' => 2,
                'shift_type_id' => 2,
                'emp_sal' => 17500,
                'staies_address' => 'Ankara / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 3,
                'zketo_code' => 1003,
                'emp_name' => 'Mehmet Kaya',
                'emp_gender' => 1,
                'branch_id' => 3,
                'emp_email' => 'mehmet.kaya@example.com',
                'emp_home_tel' => '02120000003',
                'emp_work_tel' => '08500000003',
                'notes' => 'Demo employee 3',
                'emp_start_date' => '2022-09-01',
                'Functiona_status' => 1,
                'emp_Departments_code' => 3,
                'emp_jobs_id' => 3,
                'shift_type_id' => 3,
                'emp_sal' => 22000,
                'staies_address' => 'Izmir / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 4,
                'zketo_code' => 1004,
                'emp_name' => 'Zeynep Arslan',
                'emp_gender' => 2,
                'branch_id' => 4,
                'emp_email' => 'zeynep.arslan@example.com',
                'emp_home_tel' => '02120000004',
                'emp_work_tel' => '08500000004',
                'notes' => 'Demo employee 4',
                'emp_start_date' => '2024-01-08',
                'Functiona_status' => 1,
                'emp_Departments_code' => 4,
                'emp_jobs_id' => 4,
                'shift_type_id' => 4,
                'emp_sal' => 16000,
                'staies_address' => 'Bursa / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 5,
                'zketo_code' => 1005,
                'emp_name' => 'Ali Can',
                'emp_gender' => 1,
                'branch_id' => 5,
                'emp_email' => 'ali.can@example.com',
                'emp_home_tel' => '02120000005',
                'emp_work_tel' => '08500000005',
                'notes' => 'Demo employee 5',
                'emp_start_date' => '2021-06-14',
                'Functiona_status' => 1,
                'emp_Departments_code' => 5,
                'emp_jobs_id' => 5,
                'shift_type_id' => 5,
                'emp_sal' => 25000,
                'staies_address' => 'Antalya / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 6,
                'zketo_code' => 1006,
                'emp_name' => 'Fatma Ak',
                'emp_gender' => 2,
                'branch_id' => 6,
                'emp_email' => 'fatma.ak@example.com',
                'emp_home_tel' => '02120000006',
                'emp_work_tel' => '08500000006',
                'notes' => 'Demo employee 6',
                'emp_start_date' => '2020-10-01',
                'Functiona_status' => 1,
                'emp_Departments_code' => 6,
                'emp_jobs_id' => 6,
                'shift_type_id' => 1,
                'emp_sal' => 19000,
                'staies_address' => 'Konya / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 7,
                'zketo_code' => 1007,
                'emp_name' => 'Burak Tas',
                'emp_gender' => 1,
                'branch_id' => 7,
                'emp_email' => 'burak.tas@example.com',
                'emp_home_tel' => '02120000007',
                'emp_work_tel' => '08500000007',
                'notes' => 'Demo employee 7',
                'emp_start_date' => '2019-04-22',
                'Functiona_status' => 1,
                'emp_Departments_code' => 7,
                'emp_jobs_id' => 7,
                'shift_type_id' => 2,
                'emp_sal' => 21000,
                'staies_address' => 'Samsun / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 8,
                'zketo_code' => 1008,
                'emp_name' => 'Selin Koc',
                'emp_gender' => 2,
                'branch_id' => 8,
                'emp_email' => 'selin.koc@example.com',
                'emp_home_tel' => '02120000008',
                'emp_work_tel' => '08500000008',
                'notes' => 'Demo employee 8',
                'emp_start_date' => '2024-03-01',
                'Functiona_status' => 1,
                'emp_Departments_code' => 8,
                'emp_jobs_id' => 8,
                'shift_type_id' => 3,
                'emp_sal' => 15500,
                'staies_address' => 'Eskisehir / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 9,
                'zketo_code' => 1009,
                'emp_name' => 'Emre Dogan',
                'emp_gender' => 1,
                'branch_id' => 9,
                'emp_email' => 'emre.dogan@example.com',
                'emp_home_tel' => '02120000009',
                'emp_work_tel' => '08500000009',
                'notes' => 'Demo employee 9',
                'emp_start_date' => '2018-12-10',
                'Functiona_status' => 1,
                'emp_Departments_code' => 9,
                'emp_jobs_id' => 9,
                'shift_type_id' => 4,
                'emp_sal' => 23000,
                'staies_address' => 'Adana / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
            [
                'employees_code' => 10,
                'zketo_code' => 1010,
                'emp_name' => 'Elif Cetin',
                'emp_gender' => 2,
                'branch_id' => 10,
                'emp_email' => 'elif.cetin@example.com',
                'emp_home_tel' => '02120000010',
                'emp_work_tel' => '08500000010',
                'notes' => 'Demo employee 10',
                'emp_start_date' => '2024-05-20',
                'Functiona_status' => 1,
                'emp_Departments_code' => 10,
                'emp_jobs_id' => 10,
                'shift_type_id' => 5,
                'emp_sal' => 15000,
                'staies_address' => 'Gaziantep / Turkey',
                'date' => now()->toDateString(),
                'added_by' => 1,
                'updated_by' => 1,
                'com_code' => 1,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}